### ISSUE TITLE
Does Not Properly Handle 2017 U1

### ISSUE THREAD

**Issue by Caglow** [mommermi/callhorizons#10]
A/2017 U1, which is an asteroid with a comet-like designation, is not properly parsed. A current workaround is to set .isasteroid = lambda: False before getting the ephemerides.

**Comment by mommermi** [comment]
Thanks for the issue report. I updated the parsing of comet names, which should have solved the problem. Unfortunately, Horizons does not provide a way to query the current apparition for this guy, so you will have to query it using:

    eph = callhorizons.query('2017 U1', cap=False)
    ...

Let me know if this does not work for you.
