### ISSUE TITLE
Support for state vectors

### ISSUE THREAD

**Issue by madsmh** [mommermi/callhorizons#15]
Callhorizons does not appear to support getting position vectors of the objects, for example with respect to the solar system barycenter.

**Comment by noqnio** [comment]
I would love that as well

**Comment by mommermi** [comment]
Sorry for my late reply. I have been working on an updated version of `callhorizons` and it has just been merged with `astroquery`. This new version, [`astroquery.jplhorizons`](https://astroquery.readthedocs.io/en/latest/jplhorizons/jplhorizons.html), provides state vector queries. Note that it's included in `astroquery` version 0.3.8, which is available through github, but not yet through pypi.

**Comment by noqnio** [comment]
Thank you so much for all this!!

**Comment by astrojuanlu** [comment]
Awesome @mommermi! Just to clarify, does this mean that astroquery supersedes callhorizons and that we should use that package?

**Comment by mommermi** [comment]
@Juanlu001, yes it does. It won't be a big deal for you to change your code, as the API is very similar.

I'll add a note in the `callhorizons` documentation, as well as a deprecation warning in the code.
