### ISSUE TITLE
Example from the docs does not work

### ISSUE THREAD

**Issue by astrojuanlu** [mommermi/callhorizons#17]
I was trying to reproduce this example:

```
In [2]: import callhorizons
   ...: eros = callhorizons.query('Eros')
   ...: eros.set_discreteepochs([2457446.177083, 2457446.182343])
   ...: eros.get_ephemerides(568)
   ...: print(eros['RA'], eros['DEC'])
   ...: 
   ...: 
CALLHORIZONS ERROR: run get_ephemerides or get_elements first
CALLHORIZONS ERROR: run get_ephemerides or get_elements first
None None
```

I understand that callhorizons is not going to be maintained anymore, but I tried to do the same thing in astroquery and found https://github.com/astropy/astroquery/issues/1192.

**Comment by mommermi** [comment]
Problem fixed, both here and in astroquery/jplhorizons; thanks for the issue report!

**Comment by astrojuanlu** [comment]
Thanks for your prompt response!
